In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

country   age   salary purchased
0   france  44.0  34000.0       yes
1    spain  55.0  45000.0        no
2  germany  43.0  23000.0        no
3   france  56.0  34000.0       yes
4    india  30.0  54000.0       yes

In [6]:
 x = df[['country','age','salary']].values


In [7]:
x

array([['france', 44.0, 34000.0],
       ['spain', 55.0, 45000.0],
       ['germany', 43.0, 23000.0],
       ['france', 56.0, 34000.0],
       ['india', 30.0, 54000.0],
       ['france', 30.0, nan],
       ['spain', nan, 52000.0],
       ['germany', 76.0, 12300.0],
       ['america', 54.0, 54300.0],
       ['india', nan, 36000.0],
       ['america', 58.0, 54000.0],
       ['sapin', 34.0, 32100.0],
       ['france', 43.0, 32000.0]], dtype=object)

In [8]:
y = df[['purchased']].values

In [9]:
y

array([['yes'],
       ['no'],
       ['no'],
       ['yes'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [13]:
df

country   age   salary purchased
0    france  44.0  34000.0       yes
1     spain  55.0  45000.0        no
2   germany  43.0  23000.0        no
3    france  56.0  34000.0       yes
4     india  30.0  54000.0       yes
5    france  30.0      NaN        no
6     spain   NaN  52000.0       yes
7   germany  76.0  12300.0       yes
8   america  54.0  54300.0       yes
9     india   NaN  36000.0       yes
10  america  58.0  54000.0        no
11    sapin  34.0  32100.0        no
12   france  43.0  32000.0        no

In [10]:
from sklearn.impute import SimpleImputer

In [12]:
SimpleImputer()

SimpleImputer()

In [14]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

In [16]:
imputer = imputer.fit(x[:,1:3])

In [17]:
x[:,1:3] = imputer.transform(x[:,1:3])

In [18]:
x

array([['france', 44.0, 34000.0],
       ['spain', 55.0, 45000.0],
       ['germany', 43.0, 23000.0],
       ['france', 56.0, 34000.0],
       ['india', 30.0, 54000.0],
       ['france', 30.0, 38558.333333333336],
       ['spain', 47.54545454545455, 52000.0],
       ['germany', 76.0, 12300.0],
       ['america', 54.0, 54300.0],
       ['india', 47.54545454545455, 36000.0],
       ['america', 58.0, 54000.0],
       ['sapin', 34.0, 32100.0],
       ['france', 43.0, 32000.0]], dtype=object)

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
label_x = LabelEncoder()

In [22]:
x[:,0] = label_x.fit_transform(x[:,0])

In [23]:
x

array([[1, 44.0, 34000.0],
       [5, 55.0, 45000.0],
       [2, 43.0, 23000.0],
       [1, 56.0, 34000.0],
       [3, 30.0, 54000.0],
       [1, 30.0, 38558.333333333336],
       [5, 47.54545454545455, 52000.0],
       [2, 76.0, 12300.0],
       [0, 54.0, 54300.0],
       [3, 47.54545454545455, 36000.0],
       [0, 58.0, 54000.0],
       [4, 34.0, 32100.0],
       [1, 43.0, 32000.0]], dtype=object)

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [25]:
ohc = OneHotEncoder()

In [30]:
x = ohc.fit_transform(df.country.values.reshape(-1,1)).toarray()

In [31]:
x

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [34]:
label_y = LabelEncoder()


In [36]:
y= label_y.fit_transform(y)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [37]:
y

array([1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0])

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
x_train,x_test,y_tain, y_test = train_test_split(x,y,test_size=0.2, random_state = 0)

In [40]:
from sklearn.preprocessing import StandardScaler

In [41]:
s_c = StandardScaler()

In [42]:
x_test = s_c.fit_transform(x_test)

In [43]:
x_train = s_c.fit_transform(x_train)

In [44]:
x_train


array([[ 2.        , -0.81649658, -0.5       , -0.33333333,  0.        ,
        -0.33333333],
       [-0.5       , -0.81649658,  2.        , -0.33333333,  0.        ,
        -0.33333333],
       [ 2.        , -0.81649658, -0.5       , -0.33333333,  0.        ,
        -0.33333333],
       [-0.5       , -0.81649658, -0.5       , -0.33333333,  0.        ,
         3.        ],
       [-0.5       , -0.81649658,  2.        , -0.33333333,  0.        ,
        -0.33333333],
       [-0.5       , -0.81649658, -0.5       ,  3.        ,  0.        ,
        -0.33333333],
       [-0.5       ,  1.22474487, -0.5       , -0.33333333,  0.        ,
        -0.33333333],
       [-0.5       ,  1.22474487, -0.5       , -0.33333333,  0.        ,
        -0.33333333],
       [-0.5       ,  1.22474487, -0.5       , -0.33333333,  0.        ,
        -0.33333333],
       [-0.5       ,  1.22474487, -0.5       , -0.33333333,  0.        ,
        -0.33333333]])

In [ ]:
now our dataset is ready to make model or implement algorithm